name: swift build & test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: "${{ matrix.osName }} - Swift ${{ matrix.swift-version }}"
    strategy:
      fail-fast: false
      matrix:
        os: [macos-26, ubuntu-24.04, ubuntu-22.04]
        swift-version: [6.3, 6.4.x-snapshot]
        include:
        - os: macos-26
          osName: macOS 26
        - os: ubuntu-24.04
          osName: Ubuntu 24.04
        - os: ubuntu-22.04
          osName: Ubuntu 22.04
    env:
      SWIFT_VERSION: ${{ matrix.swift-version }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install swiftly
      run: |
        case "$RUNNER_OS" in
          macOS)
            curl -L https://download.swift.org/swiftly/darwin/swiftly.pkg > swiftly.pkg
            installer -pkg swiftly.pkg -target CurrentUserHomeDirectory
            ~/.swiftly/bin/swiftly init -y --skip-install
            . "$HOME/.swiftly/env.sh"
            ;;
          Linux)
            sudo apt-get update
            sudo apt-get install -y libcurl4-openssl-dev
            if [ "${{ matrix.os }}" = "ubuntu-22.04" ]; then
              sudo apt-get install -y pkg-config python3-lldb-13
            fi
            curl -L https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz > swiftly.tar.gz
            tar zxf swiftly.tar.gz
            ./swiftly init -y --skip-install
            . "$HOME/.local/share/swiftly/env.sh"
            ;;
          *)
            echo "Unsupported OS: $RUNNER_OS"
            exit 1
            ;;
        esac
        echo "$(dirname $(which swiftly))" >> $GITHUB_PATH
    - uses: actions/checkout@v7
    - name: Install the toolchain
      run: |
        swiftly install ${{ matrix.swift-version }} -u -y
        swiftly link
    - name: Version information
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
