name: xcodebuild build & test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: "Xcode ${{ matrix.xcodeVersion }}"
    strategy:
      fail-fast: false
      matrix:
        os: [macos-26, xcode-27]
        include:
        - os: macos-26
          xcodeVersion: "26.6"
        - os: xcode-27
          xcodeVersion: "27.0"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v7
    - name: Set the Xcode version
      run: xcodes select ${{ matrix.xcodeVersion }}
    - name: Version information
      run: swift --version
    - name: List schemes
      run: xcodebuild -list
    - name: Set Default Scheme
      id: set-scheme
      run: |
        scheme_list=$(xcodebuild -list -json | tr -d "\n")
        default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['workspace']['schemes'][0]")
        echo Using default scheme: $default
        echo "scheme=$default" >> $GITHUB_OUTPUT
    - name: Build for testing
      run: |
        build_settings=()
        if [[ "${{ matrix.xcodeVersion }}" == 27.* ]]; then
          build_settings+=('SWIFT_ACTIVE_COMPILATION_CONDITIONS=$(inherited) OS_27')
        fi
        xcodebuild build-for-testing \
          -scheme "${{ steps.set-scheme.outputs.scheme }}" \
          -destination "platform=macOS,arch=arm64" \
          "${build_settings[@]}"
    - name: Run tests
      run: xcodebuild test-without-building -scheme "${{ steps.set-scheme.outputs.scheme }}" -destination "platform=macOS,arch=arm64"
